use ETRADE2
SELECT * FROM sales	

SELECT COUNT(*) FROM SALES
SELECT MIN(AMOUNT) , MAX(AMOUNT),COUNT(*),SUM(AMOUNT),AVG(AMOUNT) FROM SALES 
 /*					                                 ORTALAMA	                */

 SELECT MIN(TOTALPRICE) , MAX(TOTALPRICE),COUNT(*),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES

 SELECT MIN(TOTALPRICE) , MAX(TOTALPRICE),COUNT(*),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES
 WHERE CITY='ORDU'

 SELECT MIN(TOTALPRICE) , MAX(TOTALPRICE),COUNT(*),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES
 WHERE CITY='ÝSTANBUL'


