use ETRADE
select *
from CUSTOMERS WHERE ID = 1

INSERT INTO COSTUMERS
(COSTUMERNAME,CITY,BIRTDATE,DISTRICT,GENDER)
VALUES
('MEHMET ÖZAL','ANTALYA','1999-12-01','ALANYA','E')

SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS
SET NATÝON='US', AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

DELETE FROM COSTUMERS 

TRUNCATE TABLE CUSTOMERS

SELECT * FROM CUSTOMERS WHERE GENDER='K'

SELECT * FROM CUSTOMERS
WHERE NOT CITY='ÝSTANBUL'

SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%AlAN%'

UPDATE CUSTOMERS SET GENDER='KADIN'
WHERE GENDER='K'

SELECT * FROM CUSTOMERS
WHERE CITY='istanbul' and AGE=20

SELECT * FROM CUSTOMERS
WHERE CITY='istanbul' OR AGE=20

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE BETWEEN '19900101' AND '19981231'

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE <='19900101' OR BIRTHDATE >='19981231'

SELECT DISTINCT AGE FROM CUSTOMERS WHERE CITY='ÝSTANBUL'

SELECT * FROM CUSTOMERS ORDER BY BIRTHDATE DESC 
SELECT * FROM CUSTOMERS ORDER BY CITY,CUSTOMERNAME DESC
SELECT * FROM CUSTOMERS ORDER BY 2 --KOLON SIRASI

SELECT TOP 50 * FROM CUSTOMERS    --KAÇ SATIR GETÝRDÝ
ORDER BY 2

SELECT TOP 1 PERCENT * FROM CUSTOMERS  --PERCENT = x10




