use ETRADE2
Select * from SALES	

 SELECT
 CITY,
   MIN(TOTALPRICE)  AS MINPRICE
 , MAX(TOTALPRICE)  AS MAXPRICE
 , COUNT(*)         AS ROW_COUNT
 , SUM(TOTALPRICE)  AS TOTALPRICE
 , AVG(TOTALPRICE)  AS AVGPRICE
 FROM SALES

 GROUP BY CITY
 ORDER BY SUM(TOTALPRICE)

 SELECT TOP 10 
 CITY , SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
 GROUP BY CITY
 ORDER BY SUM(TOTALPRICE) DESC

 --VERÝ CONVERT ETME
 SELECT CONVERT(DATE,DATE_) AS DATE2 , *
 FROM SALES WHERE CITY='ANKARA'
 ORDER BY DATE_

 UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)

 SELECT * FROM SALES 
 WHERE CITY='ANKARA' AND DATE2='2019-08-02'
 ORDER BY DATE_
 --------------------

 SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTALPRICE
 FROM SALES  WHERE CITY='ANKARA'
 GROUP BY CITY ,DATE2
 ORDER BY TOTALPRICE DESC

 SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
 WHERE DATE2='2019-01-02'
 GROUP BY DATE2,CITY
 ORDER BY DATE2,SUM(TOTALPRICE) DESC

 
 SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
 WHERE DATE2>='2019-01-02' OR DATE2 <='2019-02-02'
 GROUP BY DATE2,CITY
 ORDER BY DATE2,SUM(TOTALPRICE) DESC

 SELECT * FROM SALES

 SELECT	DATEPART(MONTH,'2019-02-02')

 UPDATE SALES SET MONTHNAME_ = '01.OCAK'    WHERE DATEPART(MONTH,DATE2)=1
 UPDATE SALES SET MONTHNAME_ = '02.ÞUBAT'   WHERE DATEPART(MONTH,DATE2)=2
 UPDATE SALES SET MONTHNAME_ = '03.MART'    WHERE DATEPART(MONTH,DATE2)=3
 UPDATE SALES SET MONTHNAME_ = '04.NÝSAN'   WHERE DATEPART(MONTH,DATE2)=4
 UPDATE SALES SET MONTHNAME_ = '05.MAYIS'   WHERE DATEPART(MONTH,DATE2)=5
 UPDATE SALES SET MONTHNAME_ = '06.HAZÝRAN' WHERE DATEPART(MONTH,DATE2)=6
 UPDATE SALES SET MONTHNAME_ = '07.TEMMUZ'  WHERE DATEPART(MONTH,DATE2)=7
 UPDATE SALES SET MONTHNAME_ = '08.AÐUSTOS' WHERE DATEPART(MONTH,DATE2)=8
 UPDATE SALES SET MONTHNAME_ = '09.EYLÜL'   WHERE DATEPART(MONTH,DATE2)=9
 UPDATE SALES SET MONTHNAME_ = '10.EKÝM'    WHERE DATEPART(MONTH,DATE2)=10
 UPDATE SALES SET MONTHNAME_ = '11.KASÝM'   WHERE DATEPART(MONTH,DATE2)=11
 UPDATE SALES SET MONTHNAME_ = '12.ARALÝK'  WHERE DATEPART(MONTH,DATE2)=12

 SELECT CITY,MONTHNAME_ ,SUM(TOTALPRICE) AS TOTALPRICE
 FROM SALES
 WHERE MONTHNAME_ = '08.AÐUSTOS'
 GROUP BY CITY,MONTHNAME_
 ORDER BY CITY,MONTHNAME_ DESC

SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4 ,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCAUNT_,
SUM(AMOUNT) AS AMOUNT
FROM SALES 
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4

SELECT CITY,COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER ,
            COUNT(DISTINCT FICHENO)      AS CUSTOMERSCOUNT ,
            COUNT(*)                     AS ITEMCOUNT
FROM SALES WHERE MONTHNAME_ = '01.OCAK'
GROUP BY CITY
ORDER BY CITY


--HAVING
 SELECT CITY , SUM(TOTALPRICE) AS TOTALPRICE , COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT			
 FROM SALES
 GROUP BY CITY
 HAVING SUM(TOTALPRICE) > 40000
 ORDER BY SUM(TOTALPRICE) DESC

 SELECT CITY , SUM(TOTALPRICE) AS TOTALPRICE , COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT			
 FROM SALES
 GROUP BY CITY
 HAVING COUNT(DISTINCT CUSTOMERNAME) > 446 AND SUM(TOTALPRICE)>300000
 ORDER BY SUM(TOTALPRICE) DESC