
SELECT * FROM USERS WHERE ID=2

SELECT * FROM ADDRESS WHERE USERID=2

SELECT U.NAMESURNAME ADSOYAD
	 , U.EMAIL  EMAÝL
	 , U.GENDER  CÝNSÝYET
	 , A.ADRESTEXT  ADRES
	 , C.COUNTRY ULKE 
	 , CT.CITY SEHIR
	 , T.TOWN ILCE
	 , D.DISTRICT SEMT
	 , A.POSTALCODE	
	 FROM 
USERS U ,ADDRESS A , COUNTRIES C , CITIES CT ,
TOWNS T , DISTRICTS D 
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID
AND T.ID = A.TOWNID AND D.ID = A.DISTRICID
AND CT.CITY LIKE 'TRABZON'
ORDER BY U.NAMESURNAME

SELECT  U.NAMESURNAME, COUNT(A.ID) AS ADRESSAYÝSÝ
                      ,COUNT(DISTINCT C.ID) AS ULKESAYÝSÝ
					  ,COUNT(DISTINCT CT.ID) AS SEHIRSAYÝSÝ
FROM 
USERS U ,ADDRESS A , COUNTRIES C , CITIES CT ,
TOWNS T , DISTRICTS D 
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID
AND T.ID = A.TOWNID AND D.ID = A.DISTRICID
GROUP BY U.NAMESURNAME
HAVING COUNT(A.ID) > 2

SELECT * FROM USERS

SELECT  CT.CITY , COUNT(U.ID) AS KULLANÝCÝSAYÝSÝ
                , COUNT(DISTINCT D.DISTRICT) AS ÝLCESAYÝSÝ
FROM 
USERS U ,ADDRESS A , COUNTRIES C , CITIES CT ,
TOWNS T , DISTRICTS D 
WHERE U.ID = A.USERID AND C.ID = A.COUNTRYID  AND CT.ID=A.CITYID
AND T.ID = A.TOWNID AND D.ID = A.DISTRICID
GROUP BY CT.CITY

----------------------------------------------------------------------
--
--                    JOIN = INNER JOIN
--
SELECT  U.NAMESURNAME, U.EMAIL
	  , A.ADRESTEXT 
	  , C.COUNTRY	
	  , CT.CITY
FROM  USERS U 

JOIN ADDRESS   A  ON    A.USERID = U.ID
JOIN COUNTRIES C  ON    C.ID     = A.COUNTRYID
JOIN CITIES    CT ON    C.ID     = CT.COUNTRYID
JOIN TOWNS     T  ON    CT.ID    = T.CITYID
JOIN DISTRICTS D  ON    T.ID     = D.TOWNID

SELECT  CT.CITY 
	  , COUNT(U.ID) AS KULLANÝCÝSAYÝSÝ
FROM  USERS U 

JOIN ADDRESS   A  ON    A.USERID = U.ID
JOIN COUNTRIES C  ON    C.ID     = A.COUNTRYID
JOIN CITIES    CT ON    C.ID     = CT.COUNTRYID
JOIN TOWNS     T  ON    CT.ID    = T.CITYID
JOIN DISTRICTS D  ON    T.ID     = D.TOWNID

GROUP BY CT.CITY

--
SELECT U.ID
     , U.USERNAME_
	 , A.CITY

FROM USERS U JOIN ADDRESS A ON A.USERID = U.ID

SELECT U.ID
     , U.USERNAME_
	 , A.CITY

FROM USERS U LEFT JOIN ADDRESS A ON A.USERID = U.ID

SELECT U.ID
     , U.USERNAME_
	 , A.CITY

FROM USERS U RIGHT JOIN ADDRESS A ON A.USERID = U.ID

SELECT U.ID
     , U.USERNAME_
	 , A.CITY

FROM USERS U FULL JOIN ADDRESS A ON A.USERID = U.ID
