--STRING ÝÞLEMLER

--ASCII VE CHAR FONKSÝYONLARI
SELECT ASCII ('Ö')
SELECT CHAR(214)
SELECT ASCII(CHAR(49))
SELECT CHAR(ASCII('Ö'))

--SUBSTRING
SELECT SUBSTRING('BERKAY OZTURK',1,6)
SELECT SUBSTRING('BERKAY OZTURK',7,11)
SELECT SUBSTRING('BERKAY OZTURK',6,6)

SELECT * FROM USERS WHERE USERNAME_ LIKE 'O%'
SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,1,1) = 'O'

SELECT * FROM USERS WHERE USERNAME_ LIKE '%O'
SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,LEN(USERNAME_),1) = 'O'
--LEN FONKSÝYONU STRÝNG UZUNLUGUNU VERÝR

--CHARINDEX
SELECT CHARINDEX('AY','BERKAY OZTURK',1)
SELECT CHARINDEX('B','BERKAY OZTURK',1)
SELECT CHARINDEX('OZTURK','BERKAY OZTURK',1)

--CONCAT STRING BIRLESTIRME
SELECT 'BERKAY' + 'OZTURK'
SELECT CONCAT('BERKAY',' ','OZTURK')
SELECT CONCAT_WS(' ','BERKAY','OZTURK')

SELECT USERNAME_ + ' ' + PASSWORD_,
	   CONCAT(USERNAME_ , ' ' , PASSWORD_) ,
	   CONCAT_WS(' ',USERNAME_,PASSWORD_)
FROM USERS 

--FORMAT
SELECT FORMAT(GETDATE(),'D','en-us')
SELECT FORMAT(GETDATE(),'d','en-us')

SELECT FORMAT(GETDATE(),'D','de-de')

--LEFT,RIGHT,LEN
SELECT LEFT ('BERKAY OZTURK',4)
SELECT RIGHT ('BERKAY OZTURK',4)
SELECT LEN('1234567890')

SELECT LEFT('BERKAY OZTURK',6) ,RIGHT('BERKAY OZTURK',6)

SELECT LEFT('BERKAY OZTURK',CHARINDEX(' ','BERKAY OZTURK')) ,
       RIGHT('BERKAY OZTURK',CHARINDEX(' ','BERKAY OZTURK'))

SELECT LEFT(NAMESURNAME,CHARINDEX(' ',NAMESURNAME)) ,
       RIGHT(NAMESURNAME,LEN(NAMESURNAME)-CHARINDEX(' ',NAMESURNAME)) 
FROM USERS 

--TRIM,LTRIM,RTRIM
SELECT TRIM('   BERKAY OZTURK   ')
SELECT LTRIM('   BERKAY OZTURK   ')
--BERKAY OZTURK   --
SELECT RTRIM('   BERKAY OZTURK   ')
--   BERKAY OZTURK--

SELECT LTRIM(RTRIM('   BERKAY OZTURK  '))
--BERKAY OZTURK--


--LOWER,UPPER,REVERSE,REPLICATE
SELECT LOWER('BERKAY')
SELECT UPPER('Berkay')
SELECT REVERSE('BERKAY OZTURK')
SELECT REPLICATE('BERKAY ',2)
 
SELECT *,REPLICATE('0',8-LEN(SIRANO))+CONVERT(VARCHAR,SIRANO
FROM TEST
UPDATE TEST SET SIRANO2=REPLICATE('0',8-LEN(SIRANO))+CONVERT(VARCHAR,SIRANO)
SELECT * FROM TEST

--REPLACE
SELECT 'BERKAY OZTURK'
SELECT REPLACE('BERKAY OZTURK','BERKAY','REISBERKAY')

DECLARE @CUMLE AS VARCHAR(MAX)
SET @CUMLE='Özbekistan ekonomisi, bu yýlýn ilk yarýsýnda yüzde 6,2 büyüme kaydetti. Özbekistan Devlet Ýstatistik Komitesi, ülke ekonomisine iliþkin 2021 yýlýnýn..'
SELECT LEN(@CUMLE)
SET @CUMLE=REPLACE(@CUMLE,'b','')
SELECT LEN(@CUMLE)
SELECT 150-146
SELECT @CUMLE










