CREATE DATABASE HR
USE HR
SELECT * FROM WORKERS
SELECT * FROM WORKERTRANSACTIONS
 

CREATE TABLE WORKERS(
	ID int PRIMARY KEY IDENTITY(1,1),
	WORKERCODE VARCHAR(20),
	WORKERNAME VARCHAR(50),
	GENDER VARCHAR(1),
	BIRTHDATE DATE,
	TCNO VARCHAR(11),
	WORKERBARCODE uniqueidentifier
)

CREATE TABLE WORKERTRANSACTIONS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	WORKERID INT,
	DATE_ DATE,
	IOTYPE VARCHAR(1),
	GETID INT
)

INSERT INTO WORKERS(WORKERCODE, WORKERNAME, GENDER, BIRTHDATE, TCNO, WORKERBARCODE)
			 VALUES('12345678910','BERKAY ÖZTÜRK','E','20010807','12345678910',NEWID())

INSERT INTO WORKERTRANSACTIONS(WORKERID, DATE_, IOTYPE, GETID)
				        VALUES(1,'2022-01-17 17:45:00','Ç',3)

SELECT * FROM WORKERS
SELECT * FROM WORKERTRANSACTIONS

SELECT * FROM WORKERS WHERE WORKERBARCODE = 'F77AFC0D-8186-423F-B77D-855827F1E87B'


CREATE PROCEDURE SP_CARD_CONTROL 
@WORKERBARCODE AS VARCHAR(50)
AS 
BEGIN
	SELECT * FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
END

EXEC SP_CARD_CONTROL 'F77AFC0D-8186-423F-B77D-855827F1E87B'

ALTER PROCEDURE SP_CARD_CONTROL 
@WORKERBARCODE AS VARCHAR(50)
AS 
BEGIN
   IF EXISTS
		(SELECT * FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE)
   BEGIN
		SELECT 'KART DOÐRU'
   END
   ELSE 
   BEGIN
		SELECT' KART GEÇERSÝZ'
   END
END

EXEC SP_CARD_CONTROL 'F77AFC0D-8186-423F-B77D-855827F1E87B'

ALTER PROCEDURE SP_CARD_CONTROL 
@WORKERBARCODE AS VARCHAR(50)
AS 
BEGIN
DECLARE @WORKERNAME AS VARCHAR(100)
SELECT @WORKERNAME= WORKERNAME FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
	IF @WORKERNAME IS NULL
		BEGIN
			SELECT 'KART GEÇESÝZ'
			--RAISERROR('KART GEÇERSÝZ',16,1)	
		END
	ELSE
		BEGIN
			SELECT @WORKERNAME
		END
END

CREATE PROC SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN
	DECLARE @WORKERNAME AS VARCHAR(100)
	DECLARE @WORKERID AS INT
		SELECT @WORKERNAME=WORKERNAME,@WORKERID=ID FROM WORKERS WHERE WORKERBARCODE= @WORKERBARCODE
		IF @WORKERID IS NULL
			BEGIN
				RAISERROR('OKUTULAN KART GEÇERRÝSZDÝR',16,1)
				RETURN
			END
	DECLARE @LASTIO AS VARCHAR(1)

SELECT TOP 1 @LASTIO = IOTYPE FROM WORKERTRANSACTIONS
WHERE WORKERID = 1 AND DATE_>= CONVERT(DATE,GETDATE())
ORDER BY DATE_ DESC

		IF @LASTIO=@IOTYPE
			BEGIN
				IF @IOTYPE ='G'
					BEGIN
						RAISERROR('ZATEN ÝÇERÝDE GÖRÜNÜYORSUNUZ',16,1)
						RETURN
					END
				IF @IOTYPE ='C'
					BEGIN
						RAISERROR('ZATEN ÝÇERÝDE GÖRÜNÜYORSUNUZ',16,1)
						RETURN
					END
			END

INSERT INTO WORKERTRANSACTIONS(WORKERID,DATE_,IOTYPE,GETID)
				        VALUES(@WORKERID,@DATE,@IOTYPE,@GATEID)

SELECT @WORKERNAME AS WORKERNAME,@DATE AS DATE_,@IOTYPE AS IOTYPE
END

